### ISSUE TITLE
Darstellung Karte colours

### ISSUE THREAD

**Issue by MSHY** [sventhiel/IngolStadtNatur#2]
Die Karte soll für den User in schwarz/weiss zu sehen sein. Im "Hintergrund" darf sie ruhig farbig bleiben, da das für die Auswertung nicht schlecht ist.

**Comment by sventhiel-zz** [comment]
The colorful layer of habitats is now "grey-only". 

![image](https://user-images.githubusercontent.com/11521044/30586685-14e10570-9d31-11e7-9f72-65dbbc0f1173.png)
