### ISSUE TITLE
Darstellung Begrüssungstext

### ISSUE THREAD

**Issue by MSHY** [sventhiel/IngolStadtNatur#4]
Von dem Begrüssungstext auf der ersten Seite soll lediglich noch der erste Absatz gezeigt werden, der Rest durch ein drop-down (simpler Pfeil bzw. nur "Pfeilspitze" nach unten) sichtbar werden.

**Comment by sventhiel-zz** [comment]
At Start
![image](https://user-images.githubusercontent.com/11521044/29669358-727907f8-88e3-11e7-956f-47cc11b8b96d.png)

After Click
![image](https://user-images.githubusercontent.com/11521044/29669315-49ef05bc-88e3-11e7-81ad-865de6ee3392.png)
